export const routes = {
  home: "/",
  signin: "/signin",
  register: "/register",
  profesionales: "/professionals",
  profile: "/profile",
  profile_information: "/profile/information",
  profile_account_edit: "/profile/accountEdit",
  profesionalDetail: (id: string) => `/professionalDetail/${id}`,
  como_funciona: "/como-funciona",
  ayuda: "/ayuda",
  contacto: "/contact",
  servicios: "/services",
  onboarding: "/onboarding",

  admin: "/admin",
  admin_categories: "/admin/categories",
  admin_professionals: "/admin/professionals",
  admin_users: "/admin/users",
  admin_dashboard: "/admin/dashboard",
};
