// import type { Professional } from "@/types/profesionalTypes";



//  reemplazar estos fetch por tus endpoints reales en modulo "services"
// export default async function fetchProfessionals(): Promise<Professional[]> {



//    }
  // Ejemplo hardcodeado
//   return [
//     {
//     pId: "pro_1",
//     userId: "u1",
//     speciality: "Plomero",
//     aboutMe: "Reparaciones sin rotura.",
//     longitude: null,
//     latitude: null,
//     workingRadius: 15,
//     createdAt: new Date().toISOString(),
//     location: "CABA",
//     profileImg: "https://i.pravatar.cc/150?img=1",
//     isActive: true,
//     displayName: "Juan Pérez",
//     averageRating: 4.8,
//     reviewsCount: 120,
//   },
//   {
//     pId: "pro_2",
//     userId: "u1",
//     speciality: "Plomero",
//     aboutMe: "Reparaciones sin rotura.",
//     longitude: null,
//     latitude: null,
//     workingRadius: 15,
//     createdAt: new Date().toISOString(),
//     location: "CABA",
//     profileImg: "https://i.pravatar.cc/150?img=1",
//     isActive: true,
//     displayName: "Juan Pérez",
//     averageRating: 4.8,
//     reviewsCount: 120,
//   },
//   {
//     pId: "pro_3",
//     userId: "u2",
//     speciality: "Electricista",
//     aboutMe: "Instalaciones y mantenimiento eléctrico.",
//     longitude: null,
//     latitude: null,
//     workingRadius: 20,
//     createdAt: new Date().toISOString(),
//     location: "Lanús",
//     profileImg: "https://i.pravatar.cc/150?img=2",
//     isActive: true,
//     displayName: "María Gómez",
//     averageRating: 4.6,
//     reviewsCount: 95,
//   },
//   {
//     pId: "pro_4",
//     userId: "u3",
//     speciality: "Gasista",
//     aboutMe: "Habilitado para reparaciones y conexiones de gas.",
//     longitude: null,
//     latitude: null,
//     workingRadius: 25,
//     createdAt: new Date().toISOString(),
//     location: "San Justo",
//     profileImg: "https://i.pravatar.cc/150?img=3",
//     isActive: true,
//     displayName: "Carlos Fernández",
//     averageRating: 4.7,
//     reviewsCount: 80,
//   },
//   {
//     pId: "pro_5",
//     userId: "u4",
//     speciality: "Carpintero",
//     aboutMe: "Muebles a medida y reparaciones en madera.",
//     longitude: null,
//     latitude: null,
//     workingRadius: 10,
//     createdAt: new Date().toISOString(),
//     location: "Quilmes",
//     profileImg: "https://i.pravatar.cc/150?img=4",
//     isActive: true,
//     displayName: "Luciano Rivas",
//     averageRating: 4.5,
//     reviewsCount: 70,
//   },
//   {
//     pId: "pro_6",
//     userId: "u5",
//     speciality: "Albañil",
//     aboutMe: "Construcción y arreglos de obra gruesa y fina.",
//     longitude: null,
//     latitude: null,
//     workingRadius: 30,
//     createdAt: new Date().toISOString(),
//     location: "Morón",
//     profileImg: "https://i.pravatar.cc/150?img=5",
//     isActive: true,
//     displayName: "Pedro Sánchez",
//     averageRating: 4.9,
//     reviewsCount: 150,
//   },
//   {
//     pId: "pro_7",
//     userId: "u6",
//     speciality: "Pintor",
//     aboutMe: "Interior, exterior y trabajos decorativos.",
//     longitude: null,
//     latitude: null,
//     workingRadius: 12,
//     createdAt: new Date().toISOString(),
//     location: "Avellaneda",
//     profileImg: "https://i.pravatar.cc/150?img=6",
//     isActive: true,
//     displayName: "Diego López",
//     averageRating: 4.4,
//     reviewsCount: 60,
//   },
//   {
//     pId: "pro_8",
//     userId: "u7",
//     speciality: "Cerrajero",
//     aboutMe: "Aperturas sin daño y copias de llaves.",
//     longitude: null,
//     latitude: null,
//     workingRadius: 8,
//     createdAt: new Date().toISOString(),
//     location: "Lomas de Zamora",
//     profileImg: "https://i.pravatar.cc/150?img=7",
//     isActive: true,
//     displayName: "Fernando Castro",
//     averageRating: 4.3,
//     reviewsCount: 55,
//   },
//   {
//     pId: "pro_9",
//     userId: "u8",
//     speciality: "Jardinero",
//     aboutMe: "Mantenimiento de parques y jardines.",
//     longitude: null,
//     latitude: null,
//     workingRadius: 18,
//     createdAt: new Date().toISOString(),
//     location: "Berazategui",
//     profileImg: "https://i.pravatar.cc/150?img=8",
//     isActive: true,
//     displayName: "Santiago Herrera",
//     averageRating: 4.7,
//     reviewsCount: 85,
//   },
//   ];
// }